version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: benjamintzoc
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ATM_Database
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
     - '3004:3000' 

  